services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://edumingledb_user:7tkQ7XyPOq6YuYmqVTTbnK4B2w7BQiXr@dpg-cvgs0btumphs73cvcggg-a.oregon-postgres.render.com/edumingledb
      - SPRING_DATASOURCE_USERNAME=edumingledb_user
      - SPRING_DATASOURCE_PASSWORD=7tkQ7XyPOq6YuYmqVTTbnK4B2w7BQiXr
  frontend:
    build:
      context: ./frontend
    ports:
      - "4000:4200"



